### ISSUE TITLE
getting as map vs array

### ISSUE THREAD

**Issue by wclr** [localForage-extensions/localForage-getItems#4]
If our `getItems` requests is  particular array of keys wouldn't it be logical to return corresponding (mapped) array of stored elements, instead of map key/item?

**Comment by thgreasi** [comment]
We ended up with the current implementation approach (after some discussion
in the central localforage repo) since it seems to cover more use cases. We
thought that an object used like a dictionary would be a better approach
than index matching. Moreover this api seems more symmetric to the object
parameter that seItems uses.
If you need an array you can use Object.keys() along with Array.map() or
the upcoming es7 Object.values().

> ## 
> 
> _Thodoris Greasidis_

**Comment by wclr** [comment]
Ok, btw both repos seem to lack API docs on input and output.

**Comment by thgreasi** [comment]
That's true, I have to find some time for docs... PRs are of course welcome
based over the provided examples.
Regarding your initial report, was using something like results[keys[i]](where keys the input array and results the output object og getItems), as

## a way to retrieve items by index, an inconvenience/counterproductive?

_Thodoris Greasidis_
